# Generated by Django 4.0 on 2022-03-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_comment_author_alter_comment_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='flag',
            field=models.BooleanField(default=True, verbose_name='Флаг активности'),
        ),
    ]
