# Generated by Django 4.0 on 2022-03-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisementauthor_advertisementheading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=1500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='advertisementstatus',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='advertisementtype',
            name='type',
            field=models.CharField(default='', max_length=100, verbose_name='Тип'),
        ),
    ]
